### ISSUE TITLE
Please help me, i have a error when i tried to install it 

### ISSUE THREAD

**Issue by parcelito** [Syslifters/OffSec-Reporting#1]
Please help me, i have the next error:

┌──(root㉿jp)-[/home/jp/Sysreport/deploy]
└─# curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=design
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: unknown flag: --no-TTY
See 'podman --help'

-----------------------------------------------------------------------------------------------------------------------------
My version of docker is:
┌──(root㉿jp)-[/home/jp/Sysreport/deploy]
└─# docker --version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.3.1

thank you for you help!

**Comment by aronmolnar** [comment]
You are using podman instead of Docker (which is not officially supported). Obviously podman does not support the `--no-TTY` option.
You can try to omit the option (with Docker this option is required).
